import 'package:get/get.dart';

class Language extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          //home
          'find_your': 'Find your ',
          'recipe': 'recipe',
          'search': 'Search...',
          'recipes': 'Recipes',
          'all': 'All',
          'breakfasts': 'Breakfasts',
          'dinners': 'Dinners',
          'desserts': 'Desserts',
          'fastest': 'Fastest',
          'other': 'Other',
          //favorite
          'your_fav': 'Your favorite ',
          'recipess': 'recipes',
          'you_must': 'You must first ',
          'login': 'log in',
          'yes_delete_recipe': 'Yes, delete recipe',
          'delete_recipe': 'Delete recipe',
          'are_u_sure_recipe': 'Are you sure you want to delete this recipe?',
          'save_your_first_recipe': 'Save your first recipe!',
          //account
          'email_address': 'E-mail address',
          'creation_date': 'Creation date',
          'logout': 'Logout',
          'version': 'About version',
          'contact': 'Contact us',
          'delete': 'Delete account',
          'are_u_sure': 'Are you sure you want to delete your account?',
          'cancel': 'Cancel',
          'yes_delete': 'Yes, delete account',
          'acc_deleted': 'The account has been deleted',
          'version_number': 'Version ',
          'rights': 'All rights reserved',
          'by_signing_up': 'By signing up, you agree to our ',
          'terms': 'Terms of Service',
          'and': ' and ',
          'privacy': 'Privacy Policy',
          //auth
          'incorrect_data': 'Incorrect data, user does not exist',
          'incorrect_email': 'Enter a valid e-mail',
          'pswd': 'PASSWORD',
          'pswd_length': 'The password must have a minimum of 6 characters',
          'sign_in': 'SIGN IN',
          'forgot_pswd': 'Forgot your password?',
          'create_acc': 'CREATE A NEW ACCOUNT',
          'enter_email':
              'Enter your email and we will send you a link to reset your password',
          'send': 'SEND',
          'email_in_use': 'There is already a user with the specified email',
          'different_pswd': 'The passwords given are different',
          'confirm': 'CONFIRM',
          'sign_up': 'SIGN UP',
          'have_acc': 'ALREADY HAVE AN ACCOUNT?',
          'connect_with': 'CONNECT WITH',
          'check_email': 'Check your e-mail!',
          //details
          'ingredients': 'Ingredients',
          'preparation': 'Preparation',
          'added_fav': 'Added to favorites',
          'removed_fav': 'Removed from favorites',
        },
        'pl_PL': {
          //home
          'find_your': 'Znajdź swój ',
          'recipe': 'przepis',
          'search': 'Szukaj...',
          'recipes': 'Przepisy',
          'all': 'Wszystkie',
          'breakfasts': 'Śniadania',
          'dinners': 'Obiady',
          'desserts': 'Desery',
          'fastest': 'Najszybsze',
          'other': 'Pozostałe',
          //favorite
          'your_fav': 'Twoje ulubione ',
          'recipess': 'przepisy',
          'you_must': 'Musisz się najpierw ',
          'login': 'zalogować',
          'yes_delete_recipe': 'Tak, usuń przepis',
          'delete_recipe': 'Usuń przepis',
          'are_u_sure_recipe':
              'Czy jesteś pewny, że chcesz usunąć ten przepis?',
          'save_your_first_recipe': 'Zapisz swój pierwszy przepis!',
          //account
          'email_address': 'Adres e-mail',
          'creation_date': 'Data założenia',
          'logout': 'Wyloguj',
          'version': 'Informacje o wersji',
          'contact': 'Kontakt',
          'delete': 'Usuń konto',
          'are_u_sure': 'Czy jesteś pewny, że chcesz usunąć konto?',
          'cancel': 'Anuluj',
          'yes_delete': 'Tak, usuń konto',
          'acc_deleted': 'Konto zostało usunięte',
          'version_number': 'Wersja ',
          'rights': 'Wszelkie prawa zastrzeżone',
          'by_signing_up': 'Rejestrując się, zgadzasz się z naszym ',
          'terms': 'Regulaminem świadczenia usług',
          'and': ' oraz ',
          'privacy': 'Polityką Prywatności',
          //auth
          'incorrect_data': 'Błędne dane, użytkownik nie istnieje',
          'incorrect_email': 'Wprowadź poprawny e-mail',
          'pswd': 'HASŁO',
          'pswd_length': 'Hasło musi mieć minimum 6 znaków',
          'sign_in': 'ZALOGUJ',
          'forgot_pswd': 'Zapomniałeś hasła?',
          'create_acc': 'STWÓRZ NOWE KONTO',
          'enter_email':
              'Podaj swój e-mail, a wyślemy Ci link do zresetowania hasła',
          'send': 'WYŚLIJ',
          'email_in_use': 'Już istnieje użytkownik o podanym emailu',
          'different_pswd': 'Podane hasła są różne',
          'confirm': 'POTWIERDŹ',
          'sign_up': 'ZAREJESTRUJ',
          'have_acc': 'MASZ JUŻ KONTO?',
          'connect_with': 'POŁĄCZ Z',
          'check_email': 'Sprawdź swój e-mail!',
          //details
          'ingredients': 'Składniki',
          'preparation': 'Przygotowanie',
          'added_fav': 'Dodano do ulubionych',
          'removed_fav': 'Usunięto z ulubionych',
        }
      };
}
